files formated with prettier + Eslint (some silenced errors in .eslintrc.json) init unit test for routes (front) server/static in .gitignore

diff --git a/.github/workflows/server.yaml b/.github/workflows/server.yaml
--- a/.github/workflows/server.yaml
+++ b/.github/workflows/server.yaml
@@ -21,12 +21,20 @@ jobs:
           POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
           POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
           POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
-          # POSTGRES_HOST_AUTH_METHOD: trust  # Use this only for testing
         ports:
           - 5432:5432
         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
 
     steps:
+      - name: Verify PostgreSQL secrets
+        run: |
+          if [[ -z "${{ secrets.POSTGRES_PASSWORD }}" || -z "${{ secrets.POSTGRES_USER }}" || -z "${{ secrets.POSTGRES_DB }}" ]]; then
+            echo "One or more PostgreSQL secrets are missing!"
+            exit 1
+          else
+            echo "PostgreSQL secrets are set correctly."
+          fi
+
       - name: Checkout code
         uses: actions/checkout@v4
 
@@ -40,16 +48,6 @@ jobs:
           python -m pip install --upgrade pip
           pip install ruff
           pip install -r server/requirements.txt
-
-      - name: Verify PostgreSQL secrets
-        run: |
-          if [[ -z "${{ secrets.POSTGRES_PASSWORD }}" || -z "${{ secrets.POSTGRES_USER }}" || -z "${{ secrets.POSTGRES_DB }}" ]]; then
-            echo "One or more PostgreSQL secrets are missing!"
-            exit 1
-          else
-            echo "PostgreSQL secrets are set correctly."
-          fi
-
 
       - name: Check and fix style errors
         working-directory: server/
